[dev]
  framework="svelte-kit"
  command="npm run dev"
[build]
  framework = "svelte-kit"
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"